"""add_user_phone_and_profile_tables

Revision ID: 3c4e243461f7
Revises: 392fbcc926ff
Create Date: 2025-12-11 06:16:20.756704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c4e243461f7"
down_revision: Union[str, Sequence[str], None] = "392fbcc926ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lecturer_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("department", sa.String(), nullable=False),
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("employee_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("lecturer_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_lecturer_profiles_employee_id"),
        "lecturer_profiles",
        ["employee_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_lecturer_profiles_id"),
        "lecturer_profiles",
        ["id"],
        unique=False,
    )
    op.create_table(
        "student_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.String(), nullable=False),
        sa.Column("major", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("enrollment_year", sa.Integer(), nullable=True),
        sa.Column("gpa", sa.String(), nullable=True),
        sa.Column("academic_status", sa.String(), nullable=True),
        sa.Column("student_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_student_profiles_id"),
        "student_profiles",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_profiles_student_id"),
        "student_profiles",
        ["student_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_student_profiles_student_id"), table_name="student_profiles"
    )
    op.drop_index(
        op.f("ix_student_profiles_id"), table_name="student_profiles"
    )
    op.drop_table("student_profiles")
    op.drop_index(
        op.f("ix_lecturer_profiles_id"), table_name="lecturer_profiles"
    )
    op.drop_index(
        op.f("ix_lecturer_profiles_employee_id"),
        table_name="lecturer_profiles",
    )
    op.drop_table("lecturer_profiles")
    # ### end Alembic commands ###
