"""updated the ids to uuids

Revision ID: cb0bb794be00
Revises: 3c4e243461f7
Create Date: 2025-12-11 14:00:45.647837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb0bb794be00"
down_revision: Union[str, Sequence[str], None] = "3c4e243461f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    tables_with_pks = [
        "users",
        "courses",
        "assignments",
        "course_materials",
        "lecturer_profiles",
        "student_profiles",
        "tests",
        "test_attempts",
        "assignment_submissions",
        "enrollments",
        "video_analyses",
    ]

    # 1. Drop PK ID columns and recreate as UUID
    for table in tables_with_pks:
        op.execute(f'ALTER TABLE "{table}" DROP COLUMN id CASCADE')
        op.execute(
            f"""
            ALTER TABLE "{table}"
            ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid()
            """
        )

    # 2. Recreate all FK columns as UUID
    fk_columns = {
        "assignments": ["course_id", "lecturer_id"],
        "course_materials": ["course_id"],
        "courses": ["lecturer_id"],
        "enrollments": ["student_id", "course_id"],
        "lecturer_profiles": ["user_id"],
        "student_profiles": ["user_id"],
        "tests": ["course_id", "lecturer_id"],
        "test_attempts": ["test_id", "student_id"],
        "assignment_submissions": ["assignment_id", "student_id"],
        "video_analyses": ["user_id", "course_id"],
    }

    # 3. Drop + recreate each FK column
    for table, columns in fk_columns.items():
        for col in columns:
            op.execute(f'ALTER TABLE "{table}" DROP COLUMN "{col}"')
            op.execute(
                f"""
                ALTER TABLE "{table}"
                ADD COLUMN "{col}" UUID
                """
            )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "video_analyses",
        "course_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "video_analyses",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "video_analyses",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("nextval('users_id_seq'::regclass)"),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "tests",
        "lecturer_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "tests",
        "course_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "tests",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "test_attempts",
        "student_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "test_attempts",
        "test_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "test_attempts",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "student_profiles",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "student_profiles",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "lecturer_profiles",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "lecturer_profiles",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "enrollments",
        "course_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "enrollments",
        "student_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "enrollments",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "lecturer_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("nextval('courses_id_seq'::regclass)"),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "course_materials",
        "course_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "course_materials",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignments",
        "lecturer_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignments",
        "course_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignments",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("nextval('assignments_id_seq'::regclass)"),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignment_submissions",
        "student_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignment_submissions",
        "assignment_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignment_submissions",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
